#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $(basename "$0") <source file>"
    exit 1
fi

base_name=$(basename "$1" .ika)

./release/ikac "$1"

cc -m32 -no-pie out.s

./a.out

rm out.s
rm a.out
